/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    test1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_test1
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    test2
 * Signature: (LTestBean;)LTestBean;
 */
JNIEXPORT jobject JNICALL Java_HelloWorld_test2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
