//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `common_ifs.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "common_ifs.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultValueFactoryInit<::squarepro::ifs::HostInfo> iceC_squarepro_ifs_HostInfo_init("::squarepro::ifs::HostInfo");

const ::std::string iceC_squarepro_ifs_ICommonService_ids[2] =
{
    "::Ice::Object",
    "::squarepro::ifs::ICommonService"
};
const ::std::string iceC_squarepro_ifs_ICommonService_ops[] =
{
    "getServiceHostInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name = "getServiceHostInfo";

}

bool
squarepro::ifs::ICommonService::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_squarepro_ifs_ICommonService_ids, iceC_squarepro_ifs_ICommonService_ids + 2, s);
}

::std::vector<::std::string>
squarepro::ifs::ICommonService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_squarepro_ifs_ICommonService_ids[0], &iceC_squarepro_ifs_ICommonService_ids[2]);
}

::std::string
squarepro::ifs::ICommonService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
squarepro::ifs::ICommonService::ice_staticId()
{
    static const ::std::string typeId = "::squarepro::ifs::ICommonService";
    return typeId;
}

/// \cond INTERNAL
bool
squarepro::ifs::ICommonService::_iceD_getServiceHostInfo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_serviceId;
    istr->readAll(iceP_serviceId);
    inS.endReadParams();
    auto inA = ::IceInternal::IncomingAsync::create(inS);
    auto responseCB = [inA](const ::std::shared_ptr<HostInfo>& ret)
    {
        auto ostr = inA->startWriteParams();
        ostr->writeAll(ret);
        ostr->writePendingValues();
        inA->endWriteParams();
        inA->completed();
    };
    this->getServiceHostInfoAsync(::std::move(iceP_serviceId), responseCB, inA->exception(), current);
    return false;
}
/// \endcond

/// \cond INTERNAL
bool
squarepro::ifs::ICommonService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_squarepro_ifs_ICommonService_ops, iceC_squarepro_ifs_ICommonService_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_squarepro_ifs_ICommonService_ops)
    {
        case 0:
        {
            return _iceD_getServiceHostInfo(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

squarepro::ifs::HostInfo::~HostInfo()
{
}

const ::std::string&
squarepro::ifs::HostInfo::ice_staticId()
{
    static const ::std::string typeId = "::squarepro::ifs::HostInfo";
    return typeId;
}

/// \cond INTERNAL
void
squarepro::ifs::ICommonServicePrx::_iceI_getServiceHostInfo(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<::squarepro::ifs::HostInfo>>>& outAsync, const ::std::string& iceP_serviceId, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name);
    outAsync->invoke(iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_serviceId);
        },
        nullptr,
        [](::Ice::InputStream* istr)
        {
            ::std::shared_ptr<HostInfo> ret;
            istr->readAll(ret);
            istr->readPendingValues();
            return ret;
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
squarepro::ifs::ICommonServicePrx::_newInstance() const
{
    return ::IceInternal::createProxy<ICommonServicePrx>();
}
/// \endcond

const ::std::string&
squarepro::ifs::ICommonServicePrx::ice_staticId()
{
    return ICommonService::ice_staticId();
}

#else // C++98 mapping

namespace
{

namespace
{

const ::std::string iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name = "getServiceHostInfo";

}

}

squarepro::ifs::AMD_ICommonService_getServiceHostInfo::~AMD_ICommonService_getServiceHostInfo()
{
}

/// \cond INTERNAL
IceAsync::squarepro::ifs::AMD_ICommonService_getServiceHostInfo::AMD_ICommonService_getServiceHostInfo(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::squarepro::ifs::AMD_ICommonService_getServiceHostInfo::ice_response(const ::squarepro::ifs::HostInfoPtr& ret)
{
    ::Ice::OutputStream* ostr = startWriteParams();
    ostr->write(ret);
    ostr->writePendingValues();
    endWriteParams();
    completed();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::squarepro::ifs::upCast(HostInfo* p) { return p; }

void
::IceProxy::squarepro::ifs::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< HostInfo>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new HostInfo;
        v->_copyFrom(proxy);
    }
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::squarepro::ifs::HostInfo::_newInstance() const
{
    return new HostInfo;
}
/// \endcond

const ::std::string&
IceProxy::squarepro::ifs::HostInfo::ice_staticId()
{
    return ::squarepro::ifs::HostInfo::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::squarepro::ifs::upCast(ICommonService* p) { return p; }

void
::IceProxy::squarepro::ifs::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ICommonService>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ICommonService;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::squarepro::ifs::ICommonService::_iceI_begin_getServiceHostInfo(const ::std::string& iceP_serviceId, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_serviceId);
        result->endWriteParams();
        result->invoke(iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::squarepro::ifs::HostInfoPtr
IceProxy::squarepro::ifs::ICommonService::end_getServiceHostInfo(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_squarepro_ifs_ICommonService_getServiceHostInfo_name);
    ::squarepro::ifs::HostInfoPtr ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    istr->readPendingValues();
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::squarepro::ifs::ICommonService::_newInstance() const
{
    return new ICommonService;
}
/// \endcond

const ::std::string&
IceProxy::squarepro::ifs::ICommonService::ice_staticId()
{
    return ::squarepro::ifs::ICommonService::ice_staticId();
}

squarepro::ifs::HostInfo::~HostInfo()
{
}

/// \cond INTERNAL
::Ice::Object* squarepro::ifs::upCast(HostInfo* p) { return p; }

/// \endcond
::Ice::ObjectPtr
squarepro::ifs::HostInfo::ice_clone() const
{
    ::Ice::Object* p = new HostInfo(*this);
    return p;
}

namespace
{
const ::std::string iceC_squarepro_ifs_HostInfo_ids[2] =
{
    "::Ice::Object",
    "::squarepro::ifs::HostInfo"
};

}

bool
squarepro::ifs::HostInfo::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_squarepro_ifs_HostInfo_ids, iceC_squarepro_ifs_HostInfo_ids + 2, s);
}

::std::vector< ::std::string>
squarepro::ifs::HostInfo::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_squarepro_ifs_HostInfo_ids[0], &iceC_squarepro_ifs_HostInfo_ids[2]);
}

const ::std::string&
squarepro::ifs::HostInfo::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
squarepro::ifs::HostInfo::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::squarepro::ifs::HostInfo";
    return typeId;
#else
    return iceC_squarepro_ifs_HostInfo_ids[1];
#endif
}

/// \cond STREAM
void
squarepro::ifs::HostInfo::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< HostInfo, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
squarepro::ifs::HostInfo::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HostInfo, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

namespace
{
const ::IceInternal::DefaultValueFactoryInit< ::squarepro::ifs::HostInfo> iceC_squarepro_ifs_HostInfo_init("::squarepro::ifs::HostInfo");
}

::Ice::ValueFactoryPtr
squarepro::ifs::HostInfo::ice_factory()
{
    return ::IceInternal::factoryTable->getValueFactory(::squarepro::ifs::HostInfo::ice_staticId());
}

/// \cond INTERNAL
void
squarepro::ifs::_icePatchObjectPtr(HostInfoPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = HostInfoPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(HostInfo::ice_staticId(), v);
    }
}
/// \endcond

squarepro::ifs::ICommonService::~ICommonService()
{
}

/// \cond INTERNAL
::Ice::Object* squarepro::ifs::upCast(ICommonService* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_squarepro_ifs_ICommonService_ids[2] =
{
    "::Ice::Object",
    "::squarepro::ifs::ICommonService"
};

}

bool
squarepro::ifs::ICommonService::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_squarepro_ifs_ICommonService_ids, iceC_squarepro_ifs_ICommonService_ids + 2, s);
}

::std::vector< ::std::string>
squarepro::ifs::ICommonService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_squarepro_ifs_ICommonService_ids[0], &iceC_squarepro_ifs_ICommonService_ids[2]);
}

const ::std::string&
squarepro::ifs::ICommonService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
squarepro::ifs::ICommonService::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::squarepro::ifs::ICommonService";
    return typeId;
#else
    return iceC_squarepro_ifs_ICommonService_ids[1];
#endif
}

/// \cond INTERNAL
bool
squarepro::ifs::ICommonService::_iceD_getServiceHostInfo(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_serviceId;
    istr->read(iceP_serviceId);
    inS.endReadParams();
    this->getServiceHostInfo_async(new IceAsync::squarepro::ifs::AMD_ICommonService_getServiceHostInfo(inS), iceP_serviceId, current);
    return false;
}
/// \endcond

namespace
{
const ::std::string iceC_squarepro_ifs_ICommonService_all[] =
{
    "getServiceHostInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
squarepro::ifs::ICommonService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_squarepro_ifs_ICommonService_all, iceC_squarepro_ifs_ICommonService_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_squarepro_ifs_ICommonService_all)
    {
        case 0:
        {
            return _iceD_getServiceHostInfo(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
squarepro::ifs::ICommonService::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ICommonService, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
squarepro::ifs::ICommonService::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ICommonService, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
squarepro::ifs::_icePatchObjectPtr(ICommonServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ICommonServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ICommonService::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
