/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MemoryDemo */

#ifndef _Included_MemoryDemo
#define _Included_MemoryDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MemoryDemo
 * Method:    jmalloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_MemoryDemo_jmalloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     MemoryDemo
 * Method:    jfree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MemoryDemo_jfree
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
